# elasticsearch/config/elasticsearch.yml
# Configuration for Elasticsearch 8.8.1

# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       This file overrides those defaults for your dark web crawler setup.

# ---------------------------------- Cluster -----------------------------------
cluster.name: threatintel-cluster

# ------------------------------------ Node ------------------------------------
node.name: es-node
node.roles: [ master, data, ingest ]

# ----------------------------------- Paths ------------------------------------
# Path to directory where to store the data (separate multiple locations by comma):
path.data: /usr/share/elasticsearch/data

# Path to log files:
path.logs: /usr/share/elasticsearch/logs

# ----------------------------------- Memory -----------------------------------
# Lock the memory on startup:
bootstrap.memory_lock: true

# ---------------------------------- Network -----------------------------------
# By default Elasticsearch is only accessible on localhost. Set a different
# address here to expose this node on the network:
network.host: 0.0.0.0

# By default Elasticsearch listens for HTTP traffic on the first free port it
# finds starting at 9200. Set a specific HTTP port here:
http.port: 9200

# --------------------------------- Discovery ----------------------------------
# Pass an initial list of hosts to perform discovery when this node is started:
# For single-node setups, use the following:
discovery.type: single-node

# ---------------------------------- Security ----------------------------------
# Disable security features for development (enable in production!)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Enable security for production:
# xpack.security.enabled: true
# xpack.security.transport.ssl.enabled: true
# xpack.security.http.ssl.enabled: true

# ---------------------------------- Various -----------------------------------
# Allow other plugins to extend reserved namespaces
action.destructive_requires_name: true

# ---------------------------------- Performance -------------------------------
# Thread pool settings
thread_pool:
  write:
    size: 5
    queue_size: 1000
  search:
    size: 10
    queue_size: 1000

# Indexing buffer settings
indices.memory.index_buffer_size: 20%
indices.memory.min_index_buffer_size: 96mb

# Query cache settings
indices.queries.cache.size: 15%

# Request cache settings
indices.requests.cache.size: 2%

# Fielddata cache settings
indices.fielddata.cache.size: 30%

# ---------------------------------- Monitoring --------------------------------
# Enable monitoring collection
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# ---------------------------------- Crawler Specific --------------------------
# Settings optimized for threat intelligence data

# Increase max result window for large queries
index.max_result_window: 50000

# Optimize for write-heavy workload
index.refresh_interval: 30s
index.translog.durability: async
index.translog.sync_interval: 30s

# Analyzer settings for IoCs
analysis:
  analyzer:
    ioc_analyzer:
      type: custom
      tokenizer: keyword
      filter: [lowercase, trim]
    domain_analyzer:
      type: custom
      tokenizer: domain_tokenizer
      filter: [lowercase]
  tokenizer:
    domain_tokenizer:
      type: pattern
      pattern: '\.'

# ---------------------------------- CORS Settings -----------------------------
# Enable CORS for Kibana and other tools
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, X-User"

# ---------------------------------- Slow Log ----------------------------------
# Slow log settings for performance monitoring
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 800ms
index.indexing.slowlog.threshold.index.warn: 10s
index.indexing.slowlog.threshold.index.info: 5s
