# Dark Web Threat Intelligence Feed Monitor
# Focus: Machine-readable IOC feeds for actionable alerts.

use_tor: false
tor_proxy: "socks5h://127.0.0.1:9050"

crawl_interval: 1800  # Check feeds every 30 minutes
request_delay: 8      # Be polite to free feed providers
timeout: 30

targets:
  # ===== CRITICAL: MALICIOUS URL & DOMAIN FEEDS =====
  - name: "urlhaus_domain_feed"
    url: "https://urlhaus.abuse.ch/downloads/hostfile/"
    type: "domain_feed"
    format: "text"  # This is a hosts.txt format
    enabled: true
    priority: "critical"

  - name: "openphish_feed"
    url: "https://openphish.com/feed.txt"
    type: "phishing_feed"
    format: "text"
    enabled: true
    priority: "critical"

  # ===== CRITICAL: MALWARE HASH FEEDS =====
  - name: "malware_bazaar_recent_hashes"
    url: "https://mb-api.abuse.ch/downloads/csv_recent/"
    type: "hash_feed"
    format: "csv"
    enabled: true
    priority: "critical"

  - name: "abuse_ch_ssl_blacklist"
    url: "https://sslbl.abuse.ch/blacklist/sslblacklist.csv"
    type: "hash_feed"
    format: "csv"
    enabled: true
    priority: "high"

  # ===== HIGH: MALICIOUS IP FEEDS =====
  - name: "ci_army_ips"
    url: "http://cinsscore.com/list/ci-badguys.txt"
    type: "ip_feed"
    format: "text"
    enabled: true
    priority: "high"

  - name: "blocklist_de_ips"
    url: "https://lists.blocklist.de/lists/all.txt"
    type: "ip_feed"
    format: "text"
    enabled: true
    priority: "high"

  # ===== HIGH: EXPLOITATION INTELLIGENCE =====
  - name: "cisa_known_exploited_vulns"
    url: "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"
    type: "vulnerability_feed"
    format: "json"
    enabled: true
    priority: "critical"  # This is critical intelligence

# Source priority configuration
source_priority:
  critical:
    - "urlhaus_domain_feed"
    - "openphish_feed"
    - "malware_bazaar_recent_hashes"
    - "cisa_known_exploited_vulns"
  high:
    - "abuse_ch_ssl_blacklist"
    - "ci_army_ips"
    - "blocklist_de_ips"

# Parsing configuration for different formats
parsing:
  text:
    line_delimiter: "\n"
  csv:
    delimiter: ","
    fieldnames: ["first_seen", "url", "url_status", "threat", "tags", "urlhaus_link", "reporter"]  # Example for URLhaus
  json:
    ioc_path: "$.vulnerabilities[*].cveID"  # Path for CISA KEV

# Alerting Logic (This is key! Integrates with your SIEM/EDR)
alerting:
  # The crawler's job is to COLLECT IOCs. The actual alert is generated elsewhere.
  output_file: "./collected_iocs.json"  # File to dump new IOCs
  # Your SIEM/EDR should watch this file and check for matches in your environment.

# Logging - Focus on what matters
logging:
  level: "INFO"
  log_file: "./crawler.log"
  log_iocs_collected: true  # Log how many new IOCs we got from each feed
  log_errors: true

# Performance
performance:
  max_concurrent_requests: 1
  retry_attempts: 2
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) ThreatIntelCrawler/1.0"
