services:
  tor:
    image: dperson/torproxy:latest
    container_name: torproxy
    restart: unless-stopped
    networks:
      - dw-net
    ports:
      - "9050:9050"
    volumes:
      - tor_data:/var/lib/tor

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: es
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=false        # DEV MODE: disable security for local testing
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - dw-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - dw-net
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme_grafana
    ports:
      - "3000:3000"
    networks:
      - dw-net
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - elasticsearch

  # ElastAlert2 - using a verified working image
  elastalert:
    image: jertel/elastalert2:2.15.0
    container_name: elastalert
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ./elastalert/rules:/opt/elastalert/rules
      - ./elastalert/config.yaml:/opt/elastalert/config.yaml
    depends_on:
      - elasticsearch
    networks:
      - dw-net

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: dw-crawler
    restart: unless-stopped
    environment:
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - TOR_SOCKS=tor:9050
      - USE_TOR=false
      - MAX_PAGES_PER_SEED=20
    volumes:
      - ./crawler/config:/app/config
      - ./crawler/state:/app/state
    depends_on:
      - tor
      - elasticsearch
    networks:
      - dw-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dw-api
    ports:
      - "8000:8000"
    environment:
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    volumes:
      - ./api/config:/app/config
    depends_on:
      - elasticsearch
    networks:
      - dw-net

networks:
  dw-net:
    driver: bridge

volumes:
  esdata:
  grafana_data:
  tor_data:
