# ElastAlert2 Configuration

# Elasticsearch connection
es_host: elasticsearch
es_port: 9200
es_url_prefix: ''
es_username: ''
es_password: ''
es_use_ssl: False
verify_certs: False

# ElastAlert settings
rules_folder: /opt/elastalert/rules
run_every:
  minutes: 5

buffer_time:
  minutes: 15

# Elasticsearch index for ElastAlert metadata
writeback_index: elastalert_status
writeback_alias: elastalert_alerts

# Alert index (optional)
alert_time_limit:
  days: 2

# Logging - FIXED: Use container path and simpler config
logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    elastalert:
      level: INFO
      handlers: [console]
      propagate: false
    elasticsearch:
      level: WARNING
      handlers: [console]
      propagate: false
  root:
    level: WARNING
    handlers: [console]
