# ElastAlert2 Configuration

# Elasticsearch connection
es_host: elasticsearch
es_port: 9200
es_url_prefix: ''
es_username: ''
es_password: ''

# ElastAlert settings
rules_folder: /opt/elastalert/rules
run_every:
  minutes: 5

buffer_time:
  minutes: 15

# Elasticsearch index for ElastAlert metadata
writeback_index: elastalert_status
writeback_alias: elastalert_alerts

# Alert index (optional)
alert_time_limit:
  days: 2

# Logging
logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: logline
      level: INFO
      stream: ext://sys.stderr
    file:
      class: logging.FileHandler
      formatter: logline
      level: INFO
      filename: /var/log/elastalert.log
  loggers:
    elastalert:
      level: INFO
      handlers: [console, file]
      propagate: false
    elasticsearch:
      level: WARNING
      handlers: [console, file]
      propagate: false
    elasticsearch.trace:
      level: WARNING
      handlers: [console, file]
      propagate: false
  root:
    level: INFO
    handlers: [console, file]
